Repository openshift/elasticsearch-proxy, pull requests merged in 2020-03, with the labels that each got.

#22 Require cert verification for client authentication
  pkg/proxy/http.go
Labels: approved, lgtm, release/4.5, size/XS

#23 Forward the cert subject to upstream on successful mTLS
  pkg/handlers/authorization/certificates.go
  pkg/handlers/authorization/handler.go
  pkg/handlers/authorization/handler_test.go
  pkg/proxy/server.go
Labels: approved, lgtm, size/M

#24 Retrieve user info from: bearertoken, certificate subject
  pkg/handlers/authorization/handler.go
  pkg/handlers/authorization/handler_test.go
  pkg/proxy/http.go
Labels: approved, lgtm, size/L

#25 Serve metrics on separate listener with injected PKI
  cmd/proxy/main.go
  go.mod
  go.sum
  pkg/config/flags.go
  pkg/config/options.go
  pkg/config/options_test.go
  pkg/handlers/logging/handler.go
  pkg/proxy/http.go
  pkg/proxy/keep_alive.go
  pkg/proxy/metrics.go
Labels: approved, lgtm, size/L

#27 Update OWNERS
  OWNERS
Labels: approved, lgtm

#26 Updated AuthorizationHandler to add X-Forwarded-For header to request
  pkg/clients/openshift.go
  pkg/handlers/authorization/handler.go
  pkg/handlers/authorization/handler_test.go
Labels: approved, lgtm, size/XS

#28 Add response logger
  cmd/proxy/main.go
  pkg/handlers/authorization/handler.go
  pkg/proxy/keep_alive.go
  pkg/proxy/metrics.go
  pkg/proxy/response_handler.go
  pkg/proxy/server.go
Labels: approved, lgtm

#31 fix for use with buildah
  Dockerfile
Labels: approved, lgtm

#30 fix up logger usage
  cmd/proxy/main.go
  pkg/handlers/types.go
  pkg/proxy/http.go
  pkg/proxy/metrics.go
  pkg/proxy/server.go
Labels: approved, lgtm, release/4.5
