Repository openshift/elasticsearch-proxy, pull requests merged in 2020-09, with the labels that each got.

#46 Reduce Verbosity of logs
  pkg/proxy/server.go
Labels: approved, bugzilla/valid-bug, lgtm

#47 Bug 1879748: return 401 from api server
  pkg/handlers/authorization/handler.go
  pkg/handlers/authorization/roles_projects_service.go
  pkg/handlers/types.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#49 Add review guidelines from source google doc
  README.md
  REVIEW.md
Labels: approved, lgtm
