Repository openshift/elasticsearch-proxy, pull requests merged in 2021-02, with the labels that each got.

#73 Bug 1908707: fluentd fails to deliver message with Server returned nothing
  pkg/config/flags.go
  pkg/config/options.go
  pkg/config/options_test.go
  pkg/proxy/http.go
  pkg/proxy/server.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#71 Bug 1913802: Quote individual project names in proxy header
  pkg/handlers/authorization/handler.go
  pkg/handlers/authorization/handler_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, release/4.5

#76 Update container registry to registry.ci.openshift.org
  Dockerfile
  test/Dockerfile
Labels: approved, bugzilla/valid-bug, lgtm

#74 Bug 1924258: fluentd fails to deliver message with Server returned nothing
  pkg/config/flags.go
  pkg/config/options.go
  pkg/config/options_test.go
  pkg/proxy/http.go
  pkg/proxy/server.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm, release/4.6

#75 Bug 1924329: fluentd fails to deliver message with Server returned nothing
  pkg/config/flags.go
  pkg/config/options.go
  pkg/config/options_test.go
  pkg/proxy/http.go
  pkg/proxy/server.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm, release/4.5
